- hosts: all

  vars:
    target: 192.168.33.11

  tasks:
  - name: install prerequisites through yum
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - git
    - sshpass
    - ansible-lint
    - graphviz
    - python-pip
    - policycoreutils-python
    become: yes

  - name: install prerequisites through pip
    pip:
      name: ansible-inventory-grapher
      state: present
    become: yes

  - name: download workshop resources
    get_url:
      url: https://github.com/willthames/devops-singapore-2016/archive/master.tar.gz
      dest: /var/tmp/master.tar.gz
      force: yes
    notify: extract workshop resources

  - meta: flush_handlers

  - name: install inventory file
    copy:
      content: "[web-devel]\ntarget ansible_host={{ target }} ansible_user=vagrant"
      dest: /home/vagrant/inventory/vagrant

  - name: create ephemeral ssh key
    command: ssh-keygen -f /home/vagrant/.ssh/ansible -N "" -C "ansible"
    args:
      creates: /home/vagrant/.ssh/ansible

  - name: install ssh config file
    template:
      src: ssh_config.j2
      dest: /home/vagrant/.ssh/config
      mode: 0600

  - name: check if ssh access to target works
    command: ssh {{ target }} echo hello
    ignore_errors: True
    register: ssh_target

  - name: copy ssh to target VM
    command: sshpass -p vagrant ssh-copy-id -i /home/vagrant/.ssh/ansible {{ target }}
    when: ssh_target|failed

  handlers:
  # Use tar as unarchive module doesn't handle --strip-components=1 correctly
  - name: extract workshop resources
    command: tar xzf /var/tmp/master.tar.gz --strip-components=2 devops-singapore-2016-master/ansible
    args:
      warn: no
      chdir: /home/vagrant